docker-compose-yaml: docker-compose.yml

project: drupal-iberia-2026

environment_variables:
  git_sha: 'true'

tasks:
  post-rollout:
    - run:
        name: drush deploy
        command: drush -y deploy
        service: cli
        shell: bash

routes:
  insecure: Redirect

environments:
  main:
    routes:
      - nginx:
          - 2026.drupaliberia.eu:
              tls-acme: 'false'
              wildcard: true
              insecure: Redirect
              hsts: max-age=31536000;includeSubDomains;preload
    cronjobs:
      - name: drush cron
        schedule: "H * * * *" # This will run the cron once per hour.
        command: drush cron
        service: cli
  dev:
    cronjobs:
      - name: drush cron
        schedule: "H * * * *" # This will run the cron once per hour.
        command: drush cron
        service: cli
