docker-compose-yaml: docker-compose.yml

project: drupal-iberia-2026

environment_variables:
  git_sha: 'true'

tasks:
  post-rollout:
    - run:
        name: drush deploy
        command: drush -y deploy
        service: cli
        shell: bash

routes:
  insecure: Redirect

environments:
  main:
    cronjobs:
      - name: drush cron
        schedule: "H * * * *" # This will run the cron once per hour.
        command: drush cron
        service: cli
  dev:
    cronjobs:
      - name: drush cron
        schedule: "H * * * *" # This will run the cron once per hour.
        command: drush cron
        service: cli
